#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'player_types'

module Player
  class Client
    include ::Thrift::Client

    def newGame()
      send_newGame()
      recv_newGame()
    end

    def send_newGame()
      send_message('newGame', NewGame_args)
    end

    def recv_newGame()
      result = receive_message(NewGame_result)
      return
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_newGame(seqid, iprot, oprot)
      args = read_args(iprot, NewGame_args)
      result = NewGame_result.new()
      @handler.newGame()
      write_result(result, oprot, 'newGame', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class NewGame_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class NewGame_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

